### ISSUE TITLE
Hovering

### ISSUE THREAD

**Issue by rexs123** [OzairP/onyx#12]
View the image provided below, when hovering over the links on the footer it is oddly only changing the color of the icon and adding a very ugly underline for such a nice design.

IMAGE REFERENCE: http://i.rexsdev.com/chrome_2016-10-04_20-35-26.png

I recommend adding a off-blue to the text on hover and removing the underline also adding a nice item delay to the hover effect would look MINT.

I recommend using this for your a and a:hover's, 

```css
a {
	font-weight: 400;
	text-decoration: none;
	transition: all 600ms ease-out 0s;
	transition-property: all;
	transition-duration: 600ms;
	transition-timing-function: ease-out;
	transition-delay: 0s;
	color: #ffa826;
}
a:hover,
a:focus {
    transition: all 600ms ease-out 0s;
    transition-property: all;
    transition-duration: 600ms;
    transition-timing-function: ease-out;
    transition-delay: 0s;
	text-decoration: none;
	color: #00a6fc;
}
a:focus {
    outline: thin dotted;
    outline: 5px auto -webkit-focus-ring-color;
    outline-offset: -2px;
}
```
